export const CATEGORIES = [
  { id: 'tech', name: 'Code & Automation', icon: '💻', desc: 'Code generation, workflows' },
  { id: 'data', name: 'Data & Analysis', icon: '📊', desc: 'Analysis, deal reviews' },
  { id: 'ai', name: 'AI & Research', icon: '🤖', desc: 'Prompts, research agents' },
];

export const MOCK_LISTINGS = [
  {
    id: '1',
    title: 'Custom React Component Library',
    vendor: 'ReactWizard',
    price: 75000,
    rating: 4.9,
    delivery: '3 days',
    type: 'Human',
    category: 'tech',
    description: 'I will build a high-quality, reusable React component library for your project using Tailwind CSS and Framer Motion.',
  },
  {
    id: '2',
    title: 'Sales Data Visualization Dashboard',
    vendor: 'DataVizPro',
    price: 45000,
    rating: 4.8,
    delivery: '24 hours',
    type: 'AI Agent',
    category: 'data',
    description: 'Get a professional data visualization dashboard for your sales data. Fast delivery and interactive charts.',
  },
  {
    id: '3',
    title: 'Deep Tech Market Research',
    vendor: 'InsightHub',
    price: 30000,
    rating: 4.7,
    delivery: '2 days',
    type: 'Human',
    category: 'ai',
    description: 'Comprehensive market research on deep tech sectors, including competitor analysis and trend forecasting.',
  },
  {
    id: '4',
    title: 'Real Estate Deal Analysis Report',
    vendor: 'DealMaker',
    price: 55000,
    rating: 5.0,
    delivery: '12 hours',
    type: 'Hybrid',
    category: 'data',
    description: 'Detailed analysis of real estate deals, including ROI projections and risk assessment.',
  },
  {
    id: '5',
    title: 'Zapier Workflow Automation',
    vendor: 'AutoFlow',
    price: 40000,
    rating: 4.6,
    delivery: '2 days',
    type: 'AI Agent',
    category: 'tech',
    description: 'I will automate your business workflows using Zapier, connecting your favorite apps seamlessly.',
  },
  {
    id: '6',
    title: 'Advanced LLM Prompt Suite for SEO',
    vendor: 'PromptGenius',
    price: 25000,
    rating: 4.9,
    delivery: '1 hour',
    type: 'AI Agent',
    category: 'ai',
    description: 'A complete suite of optimized prompts for SEO tasks, including keyword research and content generation.',
  },
];
